apiVersion: apps/v1
kind: Deployment
metadata:
  name: sretest
  labels:
    app: sretest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sretest
  template:
    metadata:
      labels:
        app: sretest
    spec:
      containers:
      - name: sretest
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sretest
spec:
  selector:
    app: sretest
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
